Infoblog/Infoblog/Models/Meetings/AllMeetingsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Infoblog.Models.Meetings
{
    public class AllMeetingsViewModel
    {
        public List<Meeting> CreatedMeetings { get; set; }
        public List<Meeting> InvitedMeetings { get; set; }
        public List<MeetingPoll> CreatedMeetingPolls { get; set; }
        public List<MeetingPoll> InvitedMeetingPolls{ get; set; }
    }
}

Infoblog/Infoblog/Models/Meetings/CreateMeetingViewModel.cs
using Infoblog.Models.Meetings;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace Infoblog.Models
{
    public class CreateMeetingViewModel
    {
        [DisplayName("Titel")]
        public string Title { get; set; }

        [DisplayName("Beskrivning")]
        public string Content { get; set; }

        public List<ApplicationUser> AllUsers { get; set; }
        public ICollection<ApplicationUser> Participants { get; set; }
        public List<MeetingTime> MeetingTimes { get; set; }
    }
}

Infoblog/Infoblog/Models/Meetings/Meeting.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Infoblog.Models
{
    public class Meeting
    {
    
        [Key]
        public int Id { get; set; }

        [DisplayName("Titel")]
        public string Title { get; set; }

        [DisplayName("Beskrivning")]
        public string Content { get; set; }

        [DisplayName("Start")]
        public DateTime Start { get; set; }

        [DisplayName("Slut")]
        public DateTime End { get; set; }

        [DisplayName("Skapad av")]
        public virtual ApplicationUser Author { get; set; }

        public virtual ICollection<ApplicationUser> Participants { get; set; }
    }
}

Infoblog/Infoblog/Models/Meetings/MeetingPoll.cs
using Infoblog.Models.Meetings;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Infoblog.Models
{
    public class MeetingPoll
    {
        [Key]
        public int Id { get; set; }

        [DisplayName("Skapad av:")]
        public virtual ApplicationUser Author { get; set; }
        [DisplayName("Titel")]
        public string Title { get; set; }
        [DisplayName("Beskrivning")]
        public string Content { get;  set; }
        public virtual ICollection<PollOption> PollOptions { get; set; }
        public virtual ICollection<ApplicationUser> Participants { get; set; }
    }
}

Infoblog/Infoblog/Models/Meetings/MeetingPollResultViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Infoblog.Models.Meetings
{
    public class MeetingPollResultViewModel
    {
        public int PollId { get; set; }
        public string AuthorId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public ICollection<PollOption> PollOptions { get; set; }
        public ICollection<ApplicationUser> Participants { get; set; }

        public string SelectedTime { get; set; }
    }
}

Infoblog/Infoblog/Models/Meetings/MeetingTIme.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Infoblog.Models.Meetings
{
    public class MeetingTime
    {
        public DateTime Date { get; set; }
        public string Start { get; set; }
        public string End { get; set; }
    }
}

Infoblog/Infoblog/Models/Meetings/MeetingViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Infoblog.Models.Meetings
{
    public class MeetingViewModel
    {
        public List<MeetingPoll> CreatedMeetingPolls { get; set; }
        public List<MeetingPoll> InvitedMeetingPolls{ get; set; }
    }
}

Infoblog/Infoblog/Models/Meetings/PollOption.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Infoblog.Models.Meetings
{
    public class PollOption
    {
        [Key]
        public int Id { get; set; }

        public DateTime Start { get; set; }
        public DateTime End { get; set; }
        public int Votes { get; set; }
        public int MeetingPollId { get; set; }
        public virtual MeetingPoll MeetingPoll { get; set; }

        public virtual ICollection<ApplicationUser> UserVotes { get; set; }

    }
}

Infoblog/Infoblog/Controllers/MeetingController.cs
using Infoblog.Models;
using Infoblog.Models.Meetings;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System.Web.Http;

namespace Infoblog.Controllers
{
    [System.Web.Mvc.Authorize]
    public class MeetingController : Controller
    {

        public class MeetingData
        {
            public string Title { get; set; }
            public string Content { get; set; }
            public string[] Participants { get; set; }
            public string[] MeetingTimes { get; set; }
        }

        // GET: Meeting
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var ctx = new ApplicationDbContext();
            var user = ctx.Users.FirstOrDefault(u => u.Id.Equals(userId));
            var mvm = new AllMeetingsViewModel();

            //Hämta de mötesomröstningar som den inloggade användaren är inbjuden till
            mvm.InvitedMeetingPolls = new List<MeetingPoll>();
            var pl = ctx.MeetingPolls.Select(m => new { m.Participants, MeetingPoll = m}).ToList();
            foreach(var p in pl)
            {
                if(p.Participants.Contains(user))
                {
                    mvm.InvitedMeetingPolls.Add(p.MeetingPoll);
                }
            }

            //Hämta till de möten som den inloggade användaren är inbjuden till
            mvm.InvitedMeetings = new List<Meeting>();
            var meetings = ctx.Meetings;
            var participants = meetings.Select(m => new { m, m.Participants }).ToList();
            foreach (var m in participants)
            {
               
                if (m.Participants.Contains(user))
                {
                    mvm.InvitedMeetings.Add(m.m);
                }
            }

            //Hämta användarens skapade möten
            mvm.CreatedMeetings = ctx.Meetings.Where(m => m.Author.Id.Equals(userId)).ToList();
            //Hämta användarens skapade mötesomröstningar
            mvm.CreatedMeetingPolls = ctx.MeetingPolls.Where(m => m.Author.Id.Equals(userId)).ToList();
            
            return View(mvm);
        }

        public ActionResult Create()
        {
            var ctx = new ApplicationDbContext();
            var currentUserId = User.Identity.GetUserId();
            var currentUser = ctx.Users.FirstOrDefault(u => u.Id == currentUserId);
            var allUsers = ctx.Users.OrderBy(u => u.FirstName).ToList();
            allUsers.Remove(currentUser);
            var model = new CreateMeetingViewModel
            {
                MeetingTimes = new List<MeetingTime>(),
                AllUsers = allUsers
            };
            return View(model);
        }

        public ActionResult View(int id)
        {
            var model = new ApplicationDbContext().Meetings.FirstOrDefault(m => m.Id == id);
            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var model = new ApplicationDbContext().Meetings.FirstOrDefault(m => m.Id == id);
            return View(model);
        }

        public ActionResult PollResult(int id)
        {
            var ctx = new ApplicationDbContext();
            var mp = ctx.MeetingPolls.FirstOrDefault(m => m.Id == id);
            var view = new MeetingPollResultViewModel() {
                PollId = mp.Id,
                AuthorId = mp.Author.Id,
                Title = mp.Title,
                Content = mp.Content,
                Participants = mp.Participants,
                PollOptions = mp.PollOptions
                
            };
            return View(view);
        }

        [System.Web.Mvc.HttpPost]
        public ActionResult CreateMeetingPoll([FromBody]MeetingData meetingData)
        {
            var ctx = new ApplicationDbContext();

            var userId = User.Identity.GetUserId();
            var author = ctx.Users.First(u => u.Id.Equals(userId));

            var mp = new MeetingPoll();
            mp.Title = meetingData.Title;
            mp.Content = meetingData.Content;
            mp.Author = author;
            mp.Participants = new List<ApplicationUser>();

            List<ApplicationUser> userList = new List<ApplicationUser>();
            foreach (var email in meetingData.Participants)
            {
                var user = ctx.Users.First(u => u.Email.Equals(email));
                mp.Participants.Add(user);
            }

            var pollOptions = new List<PollOption>();
            var notification = new SendEmailController();


            foreach (var time in meetingData.MeetingTimes)
            {
                var start = DateTime.Parse(time.Split(';')[0]);
                var end = DateTime.Parse(time.Split(';')[1]);

                var option = new PollOption()
                {
                    Start = start,
                    End = end,
                    Votes = 0,
                    MeetingPoll = mp
                };

                pollOptions.Add(option);
            }

            mp.PollOptions = pollOptions;

            ctx.MeetingPolls.Add(mp);
            ctx.SaveChanges();

            notification.EmailPollInvitation(mp);

            return RedirectToAction("Index");
        }

        [System.Web.Mvc.HttpPost]
        public ActionResult CreateMeeting(MeetingPollResultViewModel model)
        {
            var ctx = new ApplicationDbContext();
            var poll = ctx.MeetingPolls.FirstOrDefault(p => p.Id == model.PollId);
            var start = DateTime.Parse(model.SelectedTime.Split(';')[0]);
            var end = DateTime.Parse(model.SelectedTime.Split(';')[1]);

            var meeting = new Meeting()
            {
                Title = poll.Title,
                Content = poll.Content,
                Author = poll.Author,
                Start = start,
                End = end,
                Participants = poll.Participants.ToList()
            };

            ctx.Meetings.Add(meeting);
            ctx.MeetingPolls.Remove(poll);
            ctx.SaveChanges();
            foreach(var p in meeting.Participants.ToList())
            {
                SendEmailController.EmailMeeting(p.Email, meeting.Title, meeting.Content, meeting.Start, meeting.End);
            }
           
            return RedirectToAction("Index");
        }

        [System.Web.Mvc.HttpPost]
        public ActionResult EditMeeting(Meeting meeting)
        {
            if(ModelState.IsValid)
            {
                var ctx = new ApplicationDbContext();
                var meetingToEdit = ctx.Meetings.SingleOrDefault(m => m.Id == meeting.Id);
                meetingToEdit.Title = meeting.Title;
                meetingToEdit.Content = meeting.Content;
                ctx.SaveChanges();
            }
            return RedirectToAction("View", new { id = meeting.Id });
        }

    }
}

Infoblog/Infoblog/Controllers/VoteController.cs
using Infoblog.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Infoblog.Controllers
{
    [Authorize]
    public class VoteController : Controller
    {
        // GET: Vote
        public ActionResult ViewVote(int meetingPollId)
        {
            var ctx = new ApplicationDbContext();
            var meeting = ctx.MeetingPolls.Where(p => p.Id == meetingPollId).ToList().FirstOrDefault();
            var meetingViewModel = new MeetingPoll
                {
                    Id = meeting.Id,
                    Author = meeting.Author,
                    Content = meeting.Content,
                    Title = meeting.Title,
                    PollOptions = meeting.PollOptions,
                    Participants = meeting.Participants
                };

            return View(meetingViewModel);
        }

        //public ActionResult AddVote(int pollId, int votes, int pollOptionId)
        //{
        //    var ctx = new ApplicationDbContext();
        //    if (ModelState.IsValid)
        //    {
        //        var meeting = ctx.MeetingPolls.Where(p => pollId == p.Id).ToList().FirstOrDefault();

        //        var polloption = meeting.PollOptions.Where(p => p.Id == pollOptionId).ToList().FirstOrDefault();

        //        polloption.Votes = votes;
                
        //        /*ctx.MeetingPolls.Add(new MeetingPoll
        //        {
        //            Author = a,
        //            Title = t,
        //            Content = c,
        //            PollOptions = 
        //        });
        //         */   
        //    };
        //        ctx.SaveChanges();

            
        //    return Redirect(Request.UrlReferrer.ToString());
        //}
    }
}

Infoblog/Infoblog/Views/Meeting/Create.cshtml
@model Infoblog.Models.CreateMeetingViewModel

@Scripts.Render("~/Scripts/jquery-3.3.1.js")

@helper createDropBoxes(string hours_id, string minutes_id, string label)
{
    <div class="form-group">
        <div class="col-md-10">
            @{
                var hours = new List<SelectListItem>();
                for (int i = 0; i < 24; i++)
                {
                    string displayTxt;
                    if (i < 10)
                    {
                        displayTxt = "0" + i;
                    }
                    else
                    {
                        displayTxt = i.ToString();
                    }
                    hours.Add(new SelectListItem()
                    {

                        Text = displayTxt,
                        Value = displayTxt
                    });
                }

                var minutes = new List<SelectListItem>();
                for (int i = 0; i < 60; i++)
                {
                    string displayTxt;
                    if (i < 10)
                    {
                        displayTxt = "0" + i;
                    }
                    else
                    {
                        displayTxt = i.ToString();
                    }
                    minutes.Add(new SelectListItem()
                    {

                        Text = displayTxt,
                        Value = displayTxt
                    });
                }
            }
            <div class="form-group">
                <label class="control-label col-md-2">@label</label>
                <div class="col-md-4">
                    @Html.DropDownList(hours_id, hours, "Timmar", new { @class = "form-control" })
                </div>
                <div class="col-md-4">
                    @Html.DropDownList(minutes_id, minutes, "Minuter", new { @class = "form-control" })
                </div>
            </div>
        </div>
    </div>
}

<div class="row">
    <div class="col-lg-12">
        <h2>Skapa nytt möte</h2>
        <hr />
    </div>
</div>

<div class="row">
    <div class="col-lg-6">
        @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "meetingPollForm" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                    </div>
                </div>

                <!---Lägg till ny mötestid-->
                <div class="form-group">
                    <label class="control-label col-md-2">Datum</label>
                    <div class="col-md-10">
                        <input class="form-control" type="date" id="meetingDate" />
                    </div>
                </div>

                @createDropBoxes("startHours", "startMinutes", "Starttid")

                @createDropBoxes("endHours", "endMinutes", "Sluttid")

                <div class=" form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button id="btnAddMeetingTime" class="btn btn-default">Lägg till tid</button>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-2 control-label">Lägg till deltagare</label>
                    <select class="form-control" multiple id="selectParticipant">
                        @foreach (var u in Model.AllUsers)
                        {
                            <option value="@u.Email,@u.FirstName @u.LastName">@u.FirstName @u.LastName</option>
                        }
                    </select>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button class="btn btn-default" id="btnAddParticipant">Lägg till deltagare</button>
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
    <div class="col-lg-6">
        <table class="table table-striped table-hover" id="meetingTimeTable">
            <thead>
                <tr>
                    <th>Mötestider</th>
                </tr>
            </thead>
        </table>
        <table class="table table-striped table-hover" id="participantsTable">
            <thead>
                <tr>
                    <th>Deltagare</th>
                </tr>
            </thead>
        </table>
        <input id="createMeetingPoll" type="submit" value="Skapa mötesinbjudan" class="btn btn-default" />
    </div>

</div>

@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/Scripts/validationScripts.js")
<script type="text/javascript">
    $(function () {
        $('#selectParticipant option').qtip({
            content: {
                text: $(this).find('option:selected').val()
            },
            position: {
                target: 'mouse',
                adjust: {
                    x: 10
                }
            }
        });

        var meetingTimes = new Array();
        var participants = new Array();

        //Lägg till mötestid
        $('#btnAddMeetingTime').on('click', function (ev) {
            ev.preventDefault();

            if ($('#meetingPollForm').valid()) {
                var startTime =
                    $('#meetingDate').val() + " " +
                    $('#startHours').val() + ":" +
                    $('#startMinutes').val();

                var endTime = $('#meetingDate').val() + " " +
                    $('#endHours').val() + ":" +
                    $('#endMinutes').val();

                var meetingTime = startTime + ";" + endTime;

                var exists = (meetingTimes.indexOf(meetingTime) > -1);
                if (!exists) {

                    var row = $('<tr></tr>');
                    var start = meetingTime.split(';')[0];
                    var end = meetingTime.split(';')[1];

                    row.append('<td>' + start + " - " + end + '</td>');

                    $('#meetingTimeTable').append(row);

                    meetingTimes.push(meetingTime);
                }
                else {
                    alert("Tiden finns redan i listan!");
                }
            }


        });

        //Lägg till deltagare
        $('#btnAddParticipant').on('click', function (ev) {
            ev.preventDefault();

            $('#selectParticipant option:selected').each(function () {
                var email = $(this).val().toString().split(",")[0];
                var name = $(this).val().toString().split(",")[1];
                var invited = { Email: email, Name: name };

                var exists = participants.filter(p => (p.Email === invited.Email));
                if (exists.length === 0) {
                    participants.push(invited);
                    var row = $('<tr></tr>');
                    row.append('<td>' + invited.Name + '</td>');
                    $('#participantsTable').append(row);
                }
                else {
                    alert(invited.Name + " finns redan i listan.")
                }
            });
        });

        //Skapa mötet
        $('#createMeetingPoll').on('click', function (ev) {
            ev.preventDefault();
            if ($('#meetingPollForm').valid()) {
                var userEmails = participants.map(u => u.Email);

                var data = {
                    Title: $('#Title').val(),
                    Content: $('#Content').val(),
                    MeetingTimes: meetingTimes,
                    Participants: userEmails

                };

                $.ajax({
                    url: '/Meeting/CreateMeetingPoll',
                    type: 'POST',
                    data: data,
                    success: function () {
                        window.location.href = "/Meeting/Index"
                    },
                    error: function (response) {
                        alert("Någonting gick fel. Pröva igen!");
                    }
                });
            }
            
        });

    });

</script>

Infoblog/Infoblog/Views/Meeting/Edit.cshtml
@model Infoblog.Models.Meeting

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Ändra möte</title>
</head>
<body>
    @using (Html.BeginForm("EditMeeting", "Meeting", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <h4>Ändra möte</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Content, 10, 100, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Spara ändringar" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Tillbaka", "View", new { id = Model.Id })
    </div>
</body>
</html>

Infoblog/Infoblog/Views/Meeting/Index.cshtml
@model Infoblog.Models.Meetings.AllMeetingsViewModel
@{
    ViewBag.Title = "Möten";
}

<h2>Mina skapade möten</h2>
<p>@Html.ActionLink("Skapa nytt möte", "Create", null, new { @class = "btn btn-default" })</p>
<hr />

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Titel</th>
            <th>Skapad av</th>
            <th>Tid</th>
        </tr>
    </thead>

    @if (Model.CreatedMeetingPolls != null && Model.CreatedMeetingPolls.Count > 0)
    {

        foreach (var m in Model.CreatedMeetingPolls)
        {
            <tr>
                <td>@Html.ActionLink(m.Title, "PollResult", new { Id = m.Id })</td>
                <td>@m.Author.FirstName @m.Author.LastName</td>
                <td>Omröstning pågår</td>
            </tr>
        }
    }

    @if (Model.CreatedMeetings != null && Model.CreatedMeetings.Count > 0)
    {
        foreach (var m in Model.CreatedMeetings)
        {
            <tr>
                <td>@Html.ActionLink(m.Title, "View", new { Id = m.Id })</td>
                <td>@m.Author.FirstName @m.Author.LastName</td>
                <td>@String.Format("{0:yyyy/MM/dd: HH:mm}", m.Start) - @String.Format("{0:HH:mm}", m.End)</td>
            </tr>
        }
    }
</table>


<h2>Mina mötesinbjudningar</h2>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Titel</th>
            <th>Skapad av</th>
            <th>Tid</th>
        </tr>
    </thead>
    @if (Model.InvitedMeetingPolls != null && Model.InvitedMeetingPolls.Count > 0)
    {
        foreach (var m in Model.InvitedMeetingPolls)
        {

            <tr>
                <td>@Html.ActionLink(m.Title, "ViewVote", "Vote", new { meetingPollId = m.Id }, new { id = m.Id})</td>
                <td>@m.Author.FirstName @m.Author.LastName</td>
                <td>Omröstning Pågår</td>
            </tr>
        }
    }

    @if (Model.InvitedMeetings != null && Model.InvitedMeetings.Count > 0)
    {
        foreach (var m in Model.InvitedMeetings)
        {
            <tr>
                <td>@Html.ActionLink(m.Title, "View", new { Id = m.Id })</td>
                <td>@m.Author.FirstName @m.Author.LastName</td>
                <td>@String.Format("{0:yyyy/M/d HH:mm}", m.Start) - @String.Format("{0:HH:mm}", m.End)</td>
            </tr>
        }

    }
</table>

Infoblog/Infoblog/Views/Meeting/PollResult.cshtml
@model Infoblog.Models.Meetings.MeetingPollResultViewModel
@using Infoblog.Models;

<div class="col-md-12">
    <h4>@Model.Title</h4>
    <hr />
    <div class="col-md-6">
        <p>@Model.Content</p>
    </div>
</div>
<div class="col-md-6">
    <h4>Deltagare:</h4>
    <hr />
    <table class="table table-striped table-hover" id="meetingTimeTable">
        <thead>
            <tr>
                <th>Namn</th>
                <th>Epost</th>
            </tr>
        </thead>
        @foreach (var p in Model.Participants)
        {
            <tr>
                <td>@p.FirstName @p.LastName</td>
                <td>@p.Email</td>
            </tr>
        }
    </table>
</div>
<div class="col-md-6">
    <h4>Tidsomröstning</h4>
    <hr />
    @using (Html.BeginForm("CreateMeeting", "Meeting", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.HiddenFor(m => m.PollId, Model.PollId);

        <table class="table table-striped table-hover" id="meetingTimeTable">
            <thead>
                <tr>
                    <th>Mötestider</th>
                    <th>Antal röster</th>
                    <th>Välj tid</th>
                </tr>
            </thead>
            @foreach (var po in Model.PollOptions)
            {
                <tr>
                    <td>@po.Start - @po.End.Hour:@po.End.Minute</td>
                    <td>@po.Votes</td>
                    <td>@Html.RadioButtonFor(m => m.SelectedTime, po.Start + ";" + po.End)</td>
                </tr>
            }
        </table>
        <input id="createMeeting" type="submit" value="Bekräfta tid och skapa möte" class="btn btn-default" />

    }

</div>

Infoblog/Infoblog/Views/Meeting/View.cshtml
@model Infoblog.Models.Meeting
@using Microsoft.AspNet.Identity;


<div class="col-md-12">
    <h2>@Model.Title</h2>
    <h4>Beskrivning</h4>
    <p>@Model.Content</p>
    @if (Model.Author.Id == User.Identity.GetUserId())
    {
        <p>@Html.ActionLink("Ändra", "Edit", new { id = Model.Id }, new { @class = "btn btn-warning btn-sm" })</p>
    }
    <hr />

    <p>
        <h4>Skapare:</h4>@{ var email = "mailto:" + Model.Author.Email;}
        <a href="@email">@Model.Author.FirstName @Model.Author.LastName</a>
    </p>
    <h4>Datum:</h4> @String.Format("{0:yyyy/MM/dd}", @Model.Start)
    <h4>Tid:</h4> @String.Format("{0:HH:mm} - {1:HH:mm}", Model.Start, Model.End)


</div>
<div class="col-md-12">
    <h4>Deltagare:</h4>
    <table class="table table-striped table-hover" id="meetingTimeTable">
        <thead>
            <tr>
                <th>Namn</th>
                <th>Epost</th>
            </tr>
        </thead>
        @foreach (var p in Model.Participants)
        {
            <tr>
                <td>@p.FirstName @p.LastName</td>
                <td>@p.Email</td>
            </tr>
        }
    </table>
</div>